[build]
builder = "NIXPACKS"
watchPatterns = [
    "package.*",
    "*.*",
    "railway.toml",
    "drumline-lib/**",
    "drumline-server/**",
]


[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/health"
