name: Build Client UI and Deploy to GitHub Pages

on:
    push:
        branches: ['main']
        paths:
            - 'client/**'

    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/configure-pages@v1
              id: pages
            - uses: actions/setup-node@v3
              with:
                node-version-file: '.nvmrc'
                cache-dependency-path: './package-lock.json'
                cache: 'npm'
            - run: npm ci
              working-directory: ./drumline-lib
            - run: npm run build
              working-directory: ./drumline-lib
            - run: npm ci
              working-directory: ./drumline-client
            - run: npm run build
              working-directory: ./drumline-client
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: ./drumline-client/build

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/deploy-pages@v1
              id: deployment
